### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by tborychowski** [parallel/firestylus#1]
I'm using Firefox 16.0.2 and Firebug 1.10.5, Firestylus 0.0.4.
In the Style pane (HTML tab) I still see line numbers in the css file and not styl file.

My css file does have the media queries generated by stylus compiler, but for some reason firebug doesn't display the *.styl references.

**Comment by jkernech** [comment]
The project is not maintained anymore since all the browsers support css mapping i.e `.css.map`
